CREATE DATABASE IF NOT EXISTS hazi_feladat
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_hungarian_ci;
USE hazi_feladat;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL
)